### ISSUE TITLE
Adding WorldGuard Region to YAML list returns an Internal Error

### ISSUE THREAD

**Issue by vibrantrida** [Sashie/skript-yaml#15]
I am trying to save a WorldGuard region to a YAML file with the following code:

```yml
options:
  config: plugins/SKPlayground/config.yml

on script load:
  load yaml "{@config}" as "config"
  
command /saveregion:
  trigger:
    set yaml list "regions.%player%" from "config" to region at player
    save yaml "config"
```

It returns an `internal error` message when it reaches `save yaml "config"` saying that the current node is `null`

```
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! [Skript] Severe Error:
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Something went horribly wrong with Skript.
[20:12:51 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:12:51 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:12:51 ERROR]: #!#! Here is full list of them:
[20:12:51 ERROR]: #!#! skript-yaml
[20:12:51 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:12:51 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:12:51 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:12:51 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:12:51 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:12:51 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[20:12:51 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Stack trace:
[20:12:51 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[20:12:51 ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:78)
[20:12:51 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:320)
[20:12:51 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:155)
[20:12:51 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:167)
[20:12:51 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:247)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:706)
[20:12:51 ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.serialize(YAMLProcessor.java:372)
[20:12:51 ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.serialize(YAMLProcessor.java:369)
[20:12:51 ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.serialize(YAMLProcessor.java:365)
[20:12:51 ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.save(YAMLProcessor.java:316)
[20:12:51 ERROR]: #!#!     at me.sashie.skriptyaml.skript.EffSaveYaml.execute(EffSaveYaml.java:45)

[20:12:51 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:294)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)

[20:12:51 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[20:12:51 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)

[20:12:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:12:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:12:51 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:12:51 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[20:12:51 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[20:12:51 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:12:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[20:12:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:12:51 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [20:12:51 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:12:51 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:12:51 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Version Information:
[20:12:51 ERROR]: #!#!   Skript: 2.2-dev37c (latest)
[20:12:51 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[20:12:51 ERROR]: #!#!   Minecraft: 1.12.2
[20:12:51 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[20:12:51 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Server platform: Spigot
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Current node: null
[20:12:51 ERROR]: #!#! Current item: save yaml "config"
[20:12:51 ERROR]: #!#! Current trigger: command /saveregion (simple event) (playground.sk, line -1)
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Thread: Server thread
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! Language: english
[20:12:51 ERROR]: #!#! Link parse mode: DISABLED
[20:12:51 ERROR]: #!#!
[20:12:51 ERROR]: #!#! End of Error.
[20:12:51 ERROR]: #!#!
```

**Comment by Sashie** [comment]
I'll look into the error and get back to you
