### ISSUE TITLE
[ERROR] Fatal error in 1.14.4

### ISSUE THREAD

**Issue by SkyCraft78** [Sashie/skript-yaml#21]
Hello !
I've an error with skript-yaml wich version 1.3.2.
I have 1.14.4 spigot.
Error :
```[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:13:41] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:13:41] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:13:41] [Server thread/ERROR]: #!#! Here is full list of them:
[17:13:41] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) Vixio (http://vixio.space) TuSKe (github.com/Tuke-Nuke/TuSKe) SK-NBeeT (https://github.com/ShaneBeee/Sk-NBeeT) Kosmos (tlatoani.us/kosmos) Skellett (https://forums.skunity.com/resources/skellett.24/) PirateSK SharpSK Skent skript-mirror (https://github.com/btk5h/skript-mirror) skDragon SkStuff skUtilities (https://tim740.github.io/) skript-yaml SkQuery Ersatz 
[17:13:41] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:13:41] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:13:41] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:13:41] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:13:41] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:13:41] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Stack trace:
[17:13:41] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[17:13:41] [Server thread/ERROR]: #!#!     at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[17:13:41] [Server thread/ERROR]: #!#!     at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[17:13:41] [Server thread/ERROR]: #!#!     at java.util.jar.JarFile.getEntry(JarFile.java:240)
[17:13:41] [Server thread/ERROR]: #!#!     at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[17:13:41] [Server thread/ERROR]: #!#!     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:13:41] [Server thread/ERROR]: #!#!     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:13:41] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.skript.CondYamlFileExists$1.check(CondYamlFileExists.java:46)
[17:13:41] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.skript.CondYamlFileExists$1.check(CondYamlFileExists.java:1)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:173)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.check(VariableString.java:741)
[17:13:41] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.skript.CondYamlFileExists.check(CondYamlFileExists.java:43)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[17:13:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[17:13:41] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
[17:13:41] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:13:41] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[17:13:41] [Server thread/ERROR]: #!#!     at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:13:41] [Server thread/ERROR]: #!#!     at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[17:13:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1633)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
[17:13:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[17:13:41] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Version Information:
[17:13:41] [Server thread/ERROR]: #!#!   Skript: 2.4
[17:13:41] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:13:41] [Server thread/ERROR]: #!#!     Date: 2019-11-30
[17:13:41] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:13:41] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[17:13:41] [Server thread/ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
[17:13:41] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.0-6-amd64
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Current node: null
[17:13:41] [Server thread/ERROR]: #!#! Current item: yaml file "plugins/MythicMobs/Mobs/MobMaker.yml" does not exist
[17:13:41] [Server thread/ERROR]: #!#! Current trigger: command /loadyaml (simple event) (mm.sk, line -1)
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Thread: Server thread
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! Language: english
[17:13:41] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[17:13:41] [Server thread/ERROR]: #!#! 
[17:13:41] [Server thread/ERROR]: #!#! End of Error.
[17:13:41] [Server thread/ERROR]: #!#!```
Thanks in advance !

**Comment by Sashie** [comment]
um... this error kind of doesnt make sense considering that line of code that it trips on is the beginning of that method <https://github.com/Sashie/skript-yaml/blob/master/src/me/sashie/skriptyaml/skript/CondYamlFileExists.java#L46>
