### ISSUE TITLE
Can't use yml with Comments

### ISSUE THREAD

**Issue by qsef1256** [Sashie/skript-yaml#29]
```
# asdf
value:
```
When using yml with comments, it gives the following error.
```
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:42:10] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:42:10] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:42:10] [Server thread/ERROR]: #!#! Here is full list of them:
[22:42:10] [Server thread/ERROR]: #!#! skRayFall v1.9.25 (https://sk.rayfall.net/) skript-gui v1.3-alpha2 (https://github.com/APickledWalrus/skript-gui) SkBee v1.11.0 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.3.2 SkQuery v4.1.5 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[22:42:10] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:42:10] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:42:10] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:42:10] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:42:10] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:42:10] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Stack trace:
[22:42:10] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "line" is null
[22:42:10] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.recursiveCommentSearch(YAMLProcessor.java:225)
[22:42:10] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.recursiveCommentSearch(YAMLProcessor.java:223)
[22:42:10] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.utils.yaml.YAMLProcessor.load(YAMLProcessor.java:178)
[22:42:10] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.skript.EffLoadYaml.load(EffLoadYaml.java:97)
[22:42:10] [Server thread/ERROR]: #!#!     at me.sashie.skriptyaml.skript.EffLoadYaml.execute(EffLoadYaml.java:62)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:129)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:281)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[22:42:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[22:42:10] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:42:10] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[22:42:10] [Server thread/ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:42:10] [Server thread/ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:42:10] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:42:10] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:42:10] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[22:42:10] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1936)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031)
[22:42:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[22:42:10] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Version Information:
[22:42:10] [Server thread/ERROR]: #!#!   Skript: 2.6-alpha1 (custom version)
[22:42:10] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[22:42:10] [Server thread/ERROR]: #!#!     Date: unknown
[22:42:10] [Server thread/ERROR]: #!#!   Bukkit: 1.17-R0.1-SNAPSHOT
[22:42:10] [Server thread/ERROR]: #!#!   Minecraft: 1.17
[22:42:10] [Server thread/ERROR]: #!#!   Java: 16.0.1 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24)
[22:42:10] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Current node: null
[22:42:10] [Server thread/ERROR]: #!#! Current item: [re]load yaml "plugins/Skript/scripts/Clicker.EnchantValue.yml" as "plugins/Skript/scripts/Clicker.EnchantValue.yml"
[22:42:10] [Server thread/ERROR]: #!#! Current trigger: function Debug1 (simple event) (BugReport.sk, line 9)
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Thread: Server thread
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! Language: english
[22:42:10] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:42:10] [Server thread/ERROR]: #!#!
[22:42:10] [Server thread/ERROR]: #!#! End of Error.
[22:42:10] [Server thread/ERROR]: #!#!
```

In Spigot 1.17, Skript version: 2.6-alpha1, skript-yaml version: 1.3.2

**Comment by LowScarlet** [comment]
Use fork version, this author is dead

**Comment by Sashie** [comment]
> Use fork version, this author is dead

And who the hell are you again???

 I'm active on discord and there is an unreleased update in my channel there....

**Comment by Sashie** [comment]
That being said I'll look into this bug

**Comment by Sashie** [comment]
This should be fixed inn the next release :P
