### ISSUE TITLE
Bug: Delete all yaml files is broken

### ISSUE THREAD

**Issue by L3v3lup** [Sashie/skript-yaml#51]
How to reproduce:
```
command test:
	trigger:
		delete all yaml from directory "plugins/Config/Zaubermarkt"
```

Error:
``` java
[21:00:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin Skript v2.7.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchFieldError: delayed
        at me.sashie.skriptyaml.DelayFork.addDelayedEvent(DelayFork.java:10) ~[skript-yaml-1.5.jar:?]
        at me.sashie.skriptyaml.AsyncEffectOld.walk(AsyncEffectOld.java:29) ~[skript-yaml-1.5.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286) ~[Skript.jar:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[Skript.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

Skript Info:
``` yaml
[21:03:24 INFO]: [Skript] Server Version: git-Purpur-2062 (MC: 1.20.1)
[21:03:24 INFO]: [Skript] Skript Version: 2.7.2 (skriptlang-github)
[21:03:24 INFO]: [Skript] Installed Skript Addons:
[21:03:24 INFO]: [Skript]  - SkUniversal v2.13
[21:03:24 INFO]: [Skript]  - skript-yaml v1.5
[21:03:24 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[21:03:24 INFO]: [Skript]  - skript-db v1.3.6
[21:03:24 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[21:03:24 INFO]: [Skript]  - SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[21:03:24 INFO]: [Skript]  - ItemsAdder v3.5.0c-r5b (devs.beer)
[21:03:24 INFO]: [Skript] Installed dependencies:
[21:03:24 INFO]: [Skript]  - WorldGuard v7.0.9-SNAPSHOT+2250-fffb0c1
[21:03:24 INFO]: [Skript]  - GriefPrevention v16.18.1-7-g64b348a
```
(I have tested version 1.4.1 and 1.5.0, same outcome)

**Comment by Sashie** [comment]
What version of Skript are you using?

**Comment by L3v3lup** [comment]
sorry for the late response: As stated in the skript info-section, it's 2.7.2.

**Comment by Sashie** [comment]
fixed in next update
