### ISSUE TITLE
[1.5 bugs] can't store YAML values in variables.

### ISSUE THREAD

**Issue by azimkia** [Sashie/skript-yaml#52]
i going developed minecraft server 1.20.2 (bukkit: purpur-2095) but i have skript-yaml command error

when skript reload, not error but when i run command, happen bukkit error

my plugin list: BungeeSK, CMI, CMILib, Colorsigns, Elevator, Imags, ItemsAdder, Lonelibs, LuckPerms, ProtocalLib, Skellet, Skript, Skript-yaml, spark, Vault, VoxelSniper, WorldEdit, WorldGuard

==============================

my code(fork example):
`on script load:
    load yaml "plugins/skript-yaml/teleport.yml" as "path"
 
command /savetp:
    trigger:
        set yaml value "%player%.location" from "path" to location of player
        save yaml "path"
 
command /td:
    trigger:
        set {_test1} to yaml value "test1.2" from "path"
        broadcast "%{_test1}%"

command /test1:
    trigger:
        set yaml value "test1.2a" from "path" to "value1"
        save yaml "path"`
==============================

yaml file content:
`pnro:
    location: !location
        world: world
        x: 101762.6552829032
        y: 46.12268729632537
        z: 1000042.4889961772
        yaw: 96.4273452758789
        pitch: 25.641632080078125

test1:
    '1': value1
    '2': value1
    2a: value1`

==============================

bukkit error
`[18:54:46 ERROR]: null

org.bukkit.command.CommandException: Unhandled exception executing command 'td' in plugin Skript v2.7.3

        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]

        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]

        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1005) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.2.jar:?]

        at net.minecraft.commands.Commands.performCommand(Commands.java:338) ~[?:?]

        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]

        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2279) ~[?:?]

        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2239) ~[?:?]

        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]

        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: java.lang.IllegalAccessError: failed to access class net.kyori.adventure.text.serializer.bungeecord.SelfSerializable from class net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory (net.kyori.adventure.text.serializer.bungeecord.SelfSerializable is in unnamed module of loader 'Skript (3).jar' @d122d13; net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory is in unnamed module of loader 'Skript (3).jar' @54f20f68)

        at net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58) ~[Skript (3).jar:?]

        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]

        at com.google.gson.Gson.toJson(Gson.java:834) ~[gson-2.10.1.jar:?]

        at com.google.gson.Gson.toJson(Gson.java:812) ~[gson-2.10.1.jar:?]

        at com.google.gson.Gson.toJson(Gson.java:759) ~[gson-2.10.1.jar:?]

        at com.google.gson.Gson.toJson(Gson.java:736) ~[gson-2.10.1.jar:?]

        at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:69) ~[bungeecord-chat-1.20-R0.1-deprecated+build.14.jar:?]

        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:31) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3259) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3247) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3227) ~[purpur-1.20.2.jar:git-Purpur-2095]

        at ch.njol.skript.effects.EffBroadcast.lambda$execute$0(EffBroadcast.java:93) ~[Skript (3).jar:?]

        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]

        at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:93) ~[Skript (3).jar:?]

        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript (3).jar:?]

        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript (3).jar:?]

        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript (3).jar:?]

        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript (3).jar:?]

        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316) ~[Skript (3).jar:?]

        at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275) ~[Skript (3).jar:?]

        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286) ~[Skript (3).jar:?]

        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[Skript (3).jar:?]

        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]

        ... 23 more`

**Comment by Sashie** [comment]
I don't see any skript-yaml related error, closing for now as no followup was ever made.
