### ISSUE TITLE
Error Skript YAML

### ISSUE THREAD

**Issue by jugandomiguel** [Sashie/skript-yaml#54]
Hi, I got this error and idk if this could be a problem
[22:32:58 ERROR]: #!#! Stack trace:
[22:32:58 ERROR]: #!#! java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprParse.get(ExprParse.java:164)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:150)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.conditions.CondCompare.check(CondCompare.java:348)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.lambda$checkConditions$1(SecConditional.java:384)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[22:32:58 ERROR]: #!#!     at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[22:32:58 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.checkConditions(SecConditional.java:384)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:286)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[22:32:58 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[22:32:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[22:32:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:32:58 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:32:58 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:32:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:32:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:536)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1935)
[22:32:58 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:32:58 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[22:32:58 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:32:58 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:32:58 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[22:32:58 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[22:32:58 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1333)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1222)
[22:32:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[22:32:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! Version Information:
[22:32:58 ERROR]: #!#!   Skript: 2.8.3 (latest)
[22:32:58 ERROR]: #!#!     Flavor: skriptlang-github
[22:32:58 ERROR]: #!#!     Date: 16:23:04.254419600
[22:32:58 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[22:32:58 ERROR]: #!#!   Minecraft: 1.20.4
[22:32:58 ERROR]: #!#!   Java: 17.0.10 (OpenJDK 64-Bit Server VM 17.0.10+7)
[22:32:58 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! Server platform: Paper
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! Current node: null
[22:32:58 ERROR]: #!#! Current item: if yaml value "1.enabled" from "config" parsed as an item type is equal to the block (comparator: ConvertedComparator{first=null,comparator=ComparatorInfo{first=class ch.njol.skript.aliases.ItemType,second=class ch.njol.skript.aliases.ItemType,comparator=ch.njol.skript.classes.data.DefaultComparators$11@601497ee},second=ConverterInfo{from=interface org.bukkit.block.Block,to=class ch.njol.skript.aliases.ItemType,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$7408/0x0000023690f2ceb8@538f62e,flags=5}})
[22:32:58 ERROR]: #!#! Current trigger: click (click) (SkriptBlocker.sk, line 15)
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! Thread: Server thread
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! Language: english
[22:32:58 ERROR]: #!#! Link parse mode: DISABLED
[22:32:58 ERROR]: #!#!
[22:32:58 ERROR]: #!#! End of Error.
[22:32:58 ERROR]: #!#!

**Comment by Sashie** [comment]
Did you fix this after? It appears to be janky skript code
