### ISSUE TITLE
error in loading

### ISSUE THREAD

**Issue by juzijun233** [Sashie/skript-yaml#55]
```
[skript-yaml] Enabling skript-yaml v1.4
[11.06 11:26:27.671] 信息: [Lobby-1] [11:26:26 WARN]: java.lang.NoSuchMethodException: org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(org.yaml.snakeyaml.nodes.Tag,java.util.Map,java.lang.Boolean)
[11.06 11:26:27.807] 信息: [Lobby-1] [11:26:26 WARN]:   at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[11.06 11:26:27.808] 信息: [Lobby-1] [11:26:26 WARN]:   at !Skript-Addon[YAML]-skript-yaml[1.4].jar//me.sashie.skriptyaml.utils.yaml.SkriptYamlRepresenter.<clinit>(SkriptYamlRepresenter.java:44)
[11.06 11:26:27.808] 信息: [Lobby-1] [11:26:26 WARN]:   at !Skript-Addon[YAML]-skript-yaml[1.4].jar//me.sashie.skriptyaml.SkriptYaml.onEnable(SkriptYaml.java:136)
[11.06 11:26:27.809] 信息: [Lobby-1] [11:26:26 WARN]:   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[11.06 11:26:27.810] 信息: [Lobby-1] [11:26:26 WARN]:   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[11.06 11:26:27.811] 信息: [Lobby-1] [11:26:26 WARN]:   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11.06 11:26:27.812] 信息: [Lobby-1] [11:26:26 WARN]:   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11.06 11:26:27.812] 信息: [Lobby-1] [11:26:26 WARN]:   at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[11.06 11:26:27.813] 信息: [Lobby-1] [11:26:26 WARN]:   at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[11.06 11:26:27.814] 信息: [Lobby-1] [11:26:26 WARN]:   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[11.06 11:26:27.815] 信息: [Lobby-1] [11:26:26 WARN]:   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[11.06 11:26:27.816] 信息: [Lobby-1] [11:26:26 WARN]:   at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[11.06 11:26:27.821] 信息: [Lobby-1] [11:26:26 WARN]:   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[11.06 11:26:27.823] 信息: [Lobby-1] [11:26:26 WARN]:   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11.06 11:26:27.823] 信息: [Lobby-1] [11:26:26 WARN]:   at java.base/java.lang.Thread.run(Thread.java:1583)
[11.06 11:26:27.824] 信息: [Lobby-1] [11:26:26 ERROR]: Error occurred while enabling skript-yaml v1.4 (Is it up to date?)
[11.06 11:26:27.824] 信息: [Lobby-1] java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
[11.06 11:26:27.825] 信息: [Lobby-1]    at me.sashie.skriptyaml.utils.yaml.SkriptYamlRepresenter.<init>(SkriptYamlRepresenter.java:56) ~[!Skript-Addon[YAML]-skript-yaml[1.4].jar:?]
[11.06 11:26:27.825] 信息: [Lobby-1]    at me.sashie.skriptyaml.SkriptYaml.onEnable(SkriptYaml.java:136) ~[!Skript-Addon[YAML]-skript-yaml[1.4].jar:?]
[11.06 11:26:27.826] 信息: [Lobby-1]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[11.06 11:26:27.827] 信息: [Lobby-1]    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.827] 信息: [Lobby-1]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.828] 信息: [Lobby-1]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[11.06 11:26:27.829] 信息: [Lobby-1]    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.834] 信息: [Lobby-1]    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.834] 信息: [Lobby-1]    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.835] 信息: [Lobby-1]    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.836] 信息: [Lobby-1]    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.837] 信息: [Lobby-1]    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
[11.06 11:26:27.837] 信息: [Lobby-1]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
```

**Comment by Sashie** [comment]
Closing due to old version
